### ISSUE TITLE
Forgematica not working 1.20.1

### ISSUE THREAD

**Issue by MayhemForge** [ThinkingStudios/Litematica-Forge#62] opened 2024-05-05 21:19 UTC
After installing Forgematica and MaFglib, The mod does not work on servers of single player. I downloaded the mod off Curseforge, and I am using it with OptiFine, Origins (Forge), Caelus, and simple Voicechat in a modpack required for my server. It says it's compatible, I can even enter the config GUI, however, I do not get the text overlay when I use a stick, and pressing M does not work to open the GUI. I don't know if it's an issue with my mods, if its Neoforge acting up, or if it's simply the mod not working, but IDK what to do, and I've tried all versions of the mod compatible with the version. I am using 1.20.1 btw. What should I do and is there anything you can do to help me?

**Comment by 5pHiNxX** [comment] 2024-05-06 09:26
I have the same issue and was able to track it down to the latest MaFgLib update. When using MaFgLib version `0.1.8-mc1.20.1` everything works fine. But as soon as I update MaFgLib to version `0.1.9-mc1.20.1` Forgematica is not working anymore.

**Comment by MayhemForge** [comment] 2024-05-06 11:21
It works now, thx!

**Comment by 5pHiNxX** [comment] 2024-05-07 07:53
Duplicate of https://github.com/ThinkingStudios/Litematica-Forge/issues/61
Can be closed

**Comment by TexBlock** [comment] 2024-05-10 22:55
Duplicate of #61

**Closed as not planned by TexBlock** 2024-05-10 22:55 UTC
